# Generated by Django 5.2.5 on 2025-09-01 16:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='carrier_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='co_driver_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='phone_number',
            field=models.CharField(default='000-000-0000', max_length=20),
        ),
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('truck_number', models.CharField(blank=True, max_length=50, null=True)),
                ('trailer_number', models.CharField(blank=True, max_length=50, null=True)),
                ('eld_device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('vin_number', models.CharField(blank=True, max_length=100, null=True)),
                ('plate_number', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_info', to='core.driverprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
